### PR TITLE
Fixed jquery tab errors

### PR DESCRIPTION
**Pull request by Appleguy15**
loadtabs.js was double loading the jquery.
That is why you saw the pages at the button of the screen for a half
second.

### CODE REVIEW

**Comment by nwarmenh** [comment]
Fix it!
screen shot 2015-02-18 at 3 38 54 pm

**Comment by Appleguy15** [comment]
@nwarmenh Fixed errors

**Comment by badtzmaru** [comment]
how did you fix this if theres no commits?
acording to this, you have not changed anything? how does it work now

**Comment by Appleguy15** [comment]
@badtzmaru Nic was not getting the css.
When I tested it I had to so a full page reload.
Then it worked.

**Comment by nwarmenh** [comment]
These are not CSS errors, these are PHP errors.  I force-reloaded and am getting the same errors.

**Comment by Appleguy15** [comment]
@nwarmenh Oops I forgot to push!

**Pull request merged**
