### PR TITLE
Would you look at that

### PR DESCRIPTION
**Pull request by riverehill**
Fixed aligning issues with buttons on the main page.

### CODE REVIEW

**Comment by nwarmenh** [comment]
I merged master into this one, but seem to still have problems with column widths?

**Comment by riverehill** [comment]
The buttons are working correctly on Anthony's and I's machine.

**Comment by nwarmenh** [comment]
[sorry for the delay on this one]

I can't figure out why I'm still seeing the buttons stacked.  See attached screenshots for Chrome (with red) and Safari (uglier).
screen shot 2015-02-11 at 8 37 11 am
screen shot 2015-02-11 at 8 39 44 am

**Comment by Appleguy15** [comment]
It's because someone is offsite.

**Comment by Appleguy15** [comment]
The thing is broke.

**Comment by Appleguy15** [comment]
*Broken

**Comment by nwarmenh** [comment]
What's broken?  Are you saying that the code in its current state only makes pretty columns if nobody is offsite?  That seems like a serious bug.

**Comment by Appleguy15** [comment]
Yah

**Comment by Appleguy15** [comment]
It needs fixing.

**Comment by riverehill** [comment]
I'll handle it :smirk:

**Comment by riverehill** [comment]
OH the there's a special thing for safari with inline-flex which I'll add once I fix the stacking issue :money_with_wings:

**Comment by riverehill** [comment]
I got it working :+1: There was a inline padding style on one of the columns which was causing all the problems. committed and synced.

**Comment by riverehill** [comment]
screen shot 2015-02-11 at 11 33 55 am
There's still an issue where if the offsite location is too long it will happen again. I don't think anyone will enter anything really long though. But I'll look into this.

**Comment by nwarmenh** [comment]
Finally did it!  Merged to master.  I'll push to production with Milo Thursday afternoon.

**Pull request closed without merging**
