### PR TITLE
Viewreports data export

### PR DESCRIPTION
**Pull request by badtzmaru**
Adds an export button that allows users to download a csv containing all of their events for the year.

### CODE REVIEW

**Comment by nwarmenh** [comment]
Here's the error I get when I load a local version...
image

Warning: Cannot modify header information - headers already sent by (output started at /Users/nwarmenh/Documents/Github repositories/Attendance_System/viewreports.php:1) in /Users/nwarmenh/Documents/Github repositories/Attendance_System/viewreports.php on line 31

**Comment by badtzmaru** [comment]
Can you try making a folder called 'data' in your main directory?

**Comment by badtzmaru** [comment]
That's the only thing I can think of, we should have the same configuration, and I'm not getting any errors. @areyess maybe you can try it on your computer?

**Comment by nwarmenh** [comment]
I do have a data folder in top directory -- presumably it was created when I ran the export? The export is in there.

**Comment by badtzmaru** [comment]
Huh. That's interesting. It works for me, and I also just changed the format of the header (line 31) and it still works? Give it another shot?

**Comment by nwarmenh** [comment]
Same error.

**Comment by badtzmaru** [comment]
Hmmm. I'll try to look into it more, but I don't really know how to proceed without knowing your configuration. Maybe its a php config setting or something? Nothing even shows up as a warning in my logs.

**Comment by badtzmaru** [comment]
Since there's not really a good way to debug this as it is, I'm going to close this with the plan of finishing the feature later when I have more time.

**Pull request closed without merging**
