### PR TITLE
Leaderboards cleanup

### PR DESCRIPTION
**Pull request by badtzmaru**
- Cleaned up leaderboards main code
- Bolded the header text on the table
- Sorted the table by offsite percentage used to make the midyear students show up in the right place.

### CODE REVIEW

**Comment by nwarmenh** [comment]
FYI @badtzmaru I just implemented this and it puts our midyear student at the bottom. (See screenshot.)
image
Seems like it is successfully reverse-sorting by percentage, but it's miscalculating his percentage?
Sorry you don't have live admin access to be able to see it...

**Comment by nwarmenh** [comment]
Will dump current database for you to play with...

**Comment by nwarmenh** [comment]
Here is current events and studentdata tables...
[pscsorg_attendance (12).sql.zip](https://github.com/PSCS-Coding/Attendance_System/files/1613049/pscsorg_attendance.12.sql.zip)

**Comment by badtzmaru** [comment]
This is intentional. The percentage is how much offsite that student has used of their allotted amount. Ryan has used 0%, as per view reports. vr I switched the sorting to be by percentage instead, because this chart is supposed to help identify which students were using their offsite in an unsustainable manner. Ryan is using their offsite perfectly, its just that they started with less in the first place.

**Comment by nwarmenh** [comment]
Okay, I'll buy that. Thanks.

**Pull request merged**
