### PR TITLE
Groups

### PR DESCRIPTION
**Pull request by badtzmaru**

### CODE REVIEW

**Comment by Appleguy15** [comment]
@badtzmaru @eastonkugler Does not work.
It selects the names but when you try to sign them out it says "Please choose a student".
screen shot 2015-02-21 at 9 19 10 pm

**Comment by badtzmaru** [comment]
I don think that's eastons fault.... I don't think his thing does that

**Comment by Appleguy15** [comment]
@badtzmaru Just tested. I will not let you select anyone.

**Comment by nwarmenh** [comment]
Closing this until you get a full groups package (including admin and full UI) done.

**Pull request closed without merging**
