### PR TITLE
Timeout

### PR DESCRIPTION
**Pull request by Appleguy15**

### CODE REVIEW

**Comment by badtzmaru** [comment]
@Appleguy15 it would be helpful if you actually wrote a description of the pull, or if you at least had a name that made sense.

**Comment by nwarmenh** [comment]
It looks like you're trying to add your ConvertHours stuff here *as well as* fixing the broken contextual coloring on production.

**Comment by Appleguy15** [comment]
@nwarmenh Yes

**Comment by nwarmenh** [comment]
12h time does not convert correctly for field trips on front page

**Comment by nwarmenh** [comment]
Timepickers on single user interface still show 24h time

**Comment by nwarmenh** [comment]
No, actually they don't!  Single user is okay.

**Comment by Appleguy15** [comment]
Field trip appears to be working without any changes.

**Comment by Appleguy15** [comment]
@nwarmenh

**Pull request merged**
