### PR TITLE
New login functionality

### PR DESCRIPTION
**Pull request by Appleguy15**
We tested this and it worked!

### CODE REVIEW

**Comment by nwarmenh** [comment]
What does this do?  What should I be testing before I merge it?

**Comment by Appleguy15** [comment]
We switched it to use cookies instead of session.

**Comment by nwarmenh** [comment]
Move the inline CSS in secondary_login into a CSS file.

Also, I loaded the branch, clicked logout, then logged in with the student password, and got this:

screen shot 2015-02-03 at 9 36 49 am

**Comment by nwarmenh** [comment]
Also, why delete edit_events?  That doesn't seem related to this feature.

**Comment by Appleguy15** [comment]
I am not getting those errors. Did you refresh the page?

**Comment by Appleguy15** [comment]
was just cleaning things up

**Comment by nwarmenh** [comment]
Yes, I have refreshed the page.  The issue persists.  Perhaps we should look at this together in person?

**Comment by Appleguy15** [comment]
Sure!

**Comment by badtzmaru** [comment]
Anthony, the problem is that you check the contents of the post variable without checking if its set. You need to say if not empty first... That's the undefined offset...

**Comment by nwarmenh** [comment]
Aren't you two in class?!?  You're gonna get (me) in trouble with Andy.

**Comment by nwarmenh** [comment]
Also @Appleguy15, I think the "headers already sent" issue has to do with the fact that you call setcookie *after* you start the HTML.  All that stuff (which is, in this case, the include of the login file) has to happen  before the opening <html> tag.

**Comment by badtzmaru** [comment]
If you just do !empty it will fix most of it.

**Comment by Appleguy15** [comment]
ok, in the if statement?

**Comment by badtzmaru** [comment]
I will write it at lunch

**Comment by Appleguy15** [comment]
Hopefully fixed it. Ready for testing

**Comment by badtzmaru** [comment]
OK we tested. It seems to be OK now.

**Pull request merged**
