### PR TITLE
added MS Column

### PR DESCRIPTION
**Pull request by Appleguy15**

### CODE REVIEW

**Comment by nwarmenh** [comment]
What's your proposal for getting the MS column into the the events table?
Coordinate with @badtzmaru about other columns needed for the sticker project?

**Comment by nwarmenh** [comment]
Also, I made changes to the branch, but they aren't showing up here?

**Comment by nwarmenh** [comment]
There's something wacky with the branch name such that I can't commit to it, but it makes a duplicate branch?

**Comment by Appleguy15** [comment]
I will make a new version of this.

**Pull request closed without merging**
