### PR TITLE
View reports sort

### LINKED ISSUE #31: View reports: Sort by status?  Limit by date range?

### PR DESCRIPTION
**Pull request by badtzmaru**
added timepickers for date selection and a dropdown for status selections. Also added a note to warn people that the displayed information is now incorrect because the displayed info is also effected by the query changes. closes #31

### CODE REVIEW

**Comment by nwarmenh** [comment]
need submit button next to these controls
screen shot 2015-04-07 at 11 23 54 am

**Comment by nwarmenh** [comment]
Also most of the lines of aggregated data at the top are confusing/useless for filtered data.  Even with the disclaimer you have.

This feature is a ways from prime time.

**Comment by badtzmaru** [comment]
i think it fixed most of the problems, anything else you want?

**Comment by badtzmaru** [comment]
@nwarmenh

**Comment by badtzmaru** [comment]
i pulled master in and dealt with the merge conflicts. you can now auto merge it

**Comment by nwarmenh** [comment]
When viewing all statuses for a limited date range, the readout at the top should only have:
* Offsite used during this period
* Times late during this period
* Times absent during this period
* IS used during this period
Everything else should disappear.

When viewing only one status for *any* date range (including everything), the readout should only have:
* Amount of that status used during the period

**Comment by nwarmenh** [comment]
Offiste time counted incorrectly

**Comment by nwarmenh** [comment]
Seems to miss events for the last day of the query?
screen shot 2015-05-05 at 11 36 05 am

**Comment by nwarmenh** [comment]
When you ask to see events of a type that don't exist, the whole datepicker/submit line disappears.

**Comment by badtzmaru** [comment]
ok should be good to go. just gonna pull master back in again

**Comment by badtzmaru** [comment]
alright. auto merge is all good

**Pull request merged**
