### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by Appleguy15**
River added some css for
user.php & viewports.php

And I extended the cookie time from 1 hour to 8 hours.

### CODE REVIEW

**Comment by Appleguy15** [comment]
I was getting weird merge conflicts with attendance.css and user.php when I was pushing master into bugfixes.

**Comment by Appleguy15** [comment]
Just did a test with the new css file in master.
It did not break anything or delete anything important.
 We may need to do a manual merge. I can't seem to resolve the conflicts.

**Comment by nwarmenh** [comment]
I don't know enough about the CSS changes to be able to resolve those conflicts.  @riverehill, can you take care of merging master into this branch?

**Comment by riverehill** [comment]
Yes.

**Comment by badtzmaru** [comment]
its quite unclear what happened in this branch and that makes is very hard to merge. maybe you guys could figure out what you actually want to change because we cannot push everything because this branch is far behind master

**Comment by nwarmenh** [comment]
Yes, and please keep your branches to one feature or big fix per branch, please.

And merge master into your branch before you submit a pull request!

**Pull request closed without merging**
