### PR TITLE
Mobile mercer island css

### PR DESCRIPTION
**Pull request by riverehill**
maybe we can just merge this version now, so people don’t have to deal with shit.

### CODE REVIEW

**Comment by badtzmaru** [comment]
:+1:

**Comment by riverehill** [comment]
<3

**Comment by riverehill** [comment]
oh the thing still happens when people log in it goes to null, ill fix ssuper quick

**Comment by badtzmaru** [comment]
👌👀👌👀👌👀👌👀👌👀

**Comment by Appleguy15** [comment]
Who all approved this? @badtzmaru

**Comment by badtzmaru** [comment]
easton and i

**Comment by Appleguy15** [comment]
@badtzmaru We don't want to make any rash decisions...

**Comment by Appleguy15** [comment]
And ok..

**Comment by badtzmaru** [comment]
mobile main page is already super broke and all he changed was css

**Comment by riverehill** [comment]
photo on 12-25-14 at 11 08 pm

**Comment by badtzmaru** [comment]
:cat:

**Comment by riverehill** [comment]
🌮

**Comment by Appleguy15** [comment]
@badtzmaru Want to re-code the main attendance page for us?

**Comment by badtzmaru** [comment]
unnecessary

**Comment by eastonkugler** [comment]
shit-tier thread

**Comment by badtzmaru** [comment]
can we talk in the actual issue threads

**Pull request merged**
