### PR TITLE
Statusview datepicker

### PR DESCRIPTION
**Pull request by badtzmaru**
adds a working date/timepicker to statusview. Only changed statusview and attendance.css

### CODE REVIEW

**Comment by nwarmenh** [comment]
I think this needs some user feedback that tells for which date and time the statuses are being displayed.  (This could be used even when it's showing "current" status.)  E.g.:

Attendance status for March 13 at 2:30pm

**Comment by badtzmaru** [comment]
I added an echo, not sure if you want it styled and if so how. *Maybe this is a job for* **@riverehill**

**Comment by nwarmenh** [comment]
Hey @riverehill, I'd like all of the stuff on this page to be centered, like everything else on the site.  Ideally, if there were only three active columns, *those* would center.  Or if there were six active columns, *those* would center.  It's not trivial since the columns all float.

Would you take a stab at this?  And make the page title and input element look nice, too?

**Comment by riverehill** [comment]
I'm on it, sorry I didn't see this till now :+1:

**Comment by badtzmaru** [comment]
alright the css is done!

**Pull request merged**
