### PR TITLE
Admin 2.0

### PR DESCRIPTION
**Pull request by Appleguy15**
#45
#93
#99

### CODE REVIEW

**Comment by nwarmenh** [comment]
Why does it flash a redirect when going to admin?

**Comment by nwarmenh** [comment]
Edit button on edit holidays doesn't work

**Comment by nwarmenh** [comment]
Can't change advisor on edit students
Solve CSS issues on edit events
Maybe get @riverehill to help?

Otherwise, "she's a beaut" (maybe)

**Comment by badtzmaru** [comment]
@Appleguy15 i merged in leaderboards manually, just by adding the page. i could not get the branches to merge correctly so i did that. however it seems pretty broken with the includes atm.

**Pull request closed without merging**
