### PR TITLE
fixed calculation errors on view reports and calculateStats()

### PR DESCRIPTION
**Pull request by badtzmaru**
It turns out there was a miscalculation from when I added mid year students three years ago. Should be good to go now.

### CODE REVIEW

**Comment by badtzmaru** [comment]
This should be added soon, as Ryan is down about 40% of their offsite.

**Comment by badtzmaru** [comment]
Pull down a new database copy, your old copy probably is making it strange.

**Comment by nwarmenh** [comment]
Unless I'm mistaken, there is no way for (either of) you to be able to pull a current copy of the DB without you having server access that I don't want you to have.

Right?

**Comment by badtzmaru** [comment]
I sent him my copy.

**Pull request merged**
