### PR TITLE
Offsite text easter eggs (Read Desc)

### PR DESCRIPTION
**Pull request by Appleguy15**
NEW EASTER EGG!!!!
How this works:
Say you enter “World Pizza !pizza” I pizza icon will appear with your
text.
There are currently 10 different options but more can be added very
easily.

### CODE REVIEW

**Comment by Appleguy15** [comment]
screen shot 2015-06-29 at 8 42 31 pm

**Comment by badtzmaru** [comment]
y u do dis

**Comment by Appleguy15** [comment]
Why not?

**Comment by badtzmaru** [comment]
can you not just use the default emojis like : 
:pizza:

**Comment by Appleguy15** [comment]
They don't show up in html.

**Comment by Appleguy15** [comment]
They where having problems displaying.

**Comment by Appleguy15** [comment]
@badtzmaru Oh nevermind. Found a unicode way to do it. Updating now.

**Comment by badtzmaru** [comment]
try :pizza:

**Comment by Appleguy15** [comment]
Using this website for the html codes: http://unicode-table.com/en/sets/emoji/

**Comment by badtzmaru** [comment]
you may have to view this in your email for it to work but try :pizza:

**Comment by Appleguy15** [comment]
ok

**Comment by badtzmaru** [comment]
check this out: http://www.xn--vi8hiv.ws/

**Pull request closed without merging**
