### PR TITLE
Multiple day selection for pre-planned events

### PR DESCRIPTION
**Pull request by badtzmaru**
works even when the dates are in the wrong order. yes i wrote this after getting 4 teeth pulled.

### CODE REVIEW

**Comment by Appleguy15** [comment]
When you preplan an event a number shows up on the top of the page.
screen shot 2015-02-13 at 10 16 09 pm

**Comment by Appleguy15** [comment]
Nice :+1:

**Comment by eastonkugler** [comment]
Anthony login.php is throwing an error on line 10 and it shows up on the main page because of the include. It caused me and milo much grief please fix.

**Comment by Appleguy15** [comment]
Could you give me a screenshot. My errors are not working. @eastonkugler

**Comment by nwarmenh** [comment]
rejected!

screen shot 2015-02-18 at 3 37 17 pm

**Comment by badtzmaru** [comment]
alright @nwarmenh now try it. cant really tell if its working or not because my errors are off.

**Comment by Appleguy15** [comment]
@badtzmaru I can show you how to turn them on.

**Comment by badtzmaru** [comment]
i think its different in mamp

**Comment by Appleguy15** [comment]
@badtzmaru You have to change it in the php.ini file

**Comment by Appleguy15** [comment]
@badtzmaru For the pre planned events: No errors come up but does not allow you to only use one text field.

**Comment by badtzmaru** [comment]
I don't understand?

**Comment by Appleguy15** [comment]
@badtzmaru Like what Nic did: When you use only one of the date fields then click a button without entering any data into the second date field it does not work. 
screen shot 2015-02-18 at 5 01 18 pm

**Comment by badtzmaru** [comment]
Oh I see

**Comment by Appleguy15** [comment]
I don't know if that was intended. If not I would an error display.

**Comment by badtzmaru** [comment]
thats intended, thats how you pre plan only one day...

**Comment by badtzmaru** [comment]
@nwarmenh @Appleguy15 its now fixed

**Pull request merged**
