### PR TITLE
status view hover percentages

### PR DESCRIPTION
**Pull request by badtzmaru**
on statusview, hover over the name of a status to see more info

### CODE REVIEW

**Comment by badtzmaru** [comment]
hey @Appleguy15 @nwarmenh @eastonkugler check this out

**Comment by badtzmaru** [comment]
adds this on hover
adds

**Comment by Appleguy15** [comment]
@badtzmaru As I said, we should have it on two lines so that it does not get wide.

**Comment by badtzmaru** [comment]
i have mostly fixed this issue

**Comment by badtzmaru** [comment]
I changed the css to force width

**Pull request merged**
