### PR TITLE
Viewreports fix

### PR DESCRIPTION
**Pull request by Appleguy15**

### CODE REVIEW

**Comment by Appleguy15** [comment]
When you go to the SUI on the production server and click View Reports it does not go to your own page.

**Comment by nwarmenh** [comment]
FFR since this is the same as issue #37, I wonder if there's a way to attach pull requests to other issues?

**Comment by nwarmenh** [comment]
(bringing in @badtzmaru)

Any thoughts on how this got broken in the first place?

**Comment by Appleguy15** [comment]
(Responding for @badtzmaru ) We don't know.

**Comment by Appleguy15** [comment]
Sessions are being weird right now.

**Comment by nwarmenh** [comment]
Not ready yet -- get yer calls to session and cookies above the opening html tag.
screen shot 2015-02-06 at 12 53 03 pm

**Comment by nwarmenh** [comment]
Looks like it's because you accomplish your login redirects by sending a <meta> tag in login.php, so then when you set your cookie, it's too late.

**Pull request merged**
