### PR TITLE
allotted hours floating point fix

### PR DESCRIPTION
**Pull request by badtzmaru**
please note that your database format must be updated to accept floats instead of ints.

### CODE REVIEW

**Comment by Appleguy15** [comment]
@badtzmaru We can get this approved with @riverehill

**Comment by Appleguy15** [comment]
@badtzmaru You have my OK

**Comment by badtzmaru** [comment]
wait, you can work on attendance while in line at the apple store?

**Comment by Appleguy15** [comment]
Yeah the Apple Store has wifi.

**Comment by badtzmaru** [comment]
noice

**Comment by Appleguy15** [comment]
Checked. Remember to update this on production database.
> Look good :+1:

**Pull request merged**
