### PR TITLE
Select All button only shows up for admin

### PR DESCRIPTION
**Pull request by Appleguy15**

### CODE REVIEW

**Comment by nwarmenh** [comment]
(I want @badtzmaru, @eastonkugler, and @riverehill in on this conversation.)

I don't think this is the solution to the problem.  Why not either train the users to use it, or add some kind of JS confirm, or...?  Students need to have this functionality, especially the "deselect all" feature.

**Comment by riverehill** [comment]
I can do some kind of confirm for the button with jquery.

**Comment by badtzmaru** [comment]
He just meant a js "are you sure" type of thing

**Comment by riverehill** [comment]
Ye that's what I meant 🌺

**Comment by nwarmenh** [comment]
Agreed.  I want students to have access to this functionality.

**Pull request closed without merging**
