### PR TITLE
updated adminpage styling

### PR DESCRIPTION
**Pull request by riverehill**

### CODE REVIEW

**Comment by nwarmenh** [comment]
Not sue why this won't auto-merge.  I'm afraid to do the merge conflicts since I don't know all of what you've done.  Help?

**Comment by riverehill** [comment]
Yes, but does it look fine? the admin pages. I like the minimalist look

**Comment by badtzmaru** [comment]
what ever happened with this? if i looks good we should manually merge them

**Comment by riverehill** [comment]
i mean, i just got rid of the ugly grey color surrounded all the elements and replaced with a darker transparent grey.

**Comment by nwarmenh** [comment]
If you can make this so that it will automatically merge, I will approve it.

**Comment by riverehill** [comment]
This branch isn't really necessary anymore. I can do better css on an updated branch.

**Pull request closed without merging**
